### ISSUE TITLE
Enemy Spinning

### ISSUE THREAD

**Issue by MikeMMattinson** [nickmattinson/ZXYZ#57]
Player pushes into enemy and enemy spins around.

- [ ] change enemy dynamic, kinematic or static attribute and mass so that the enemy doesn't spin
- [x] change sorting layer of enemy to be above buffs
- [x] Add a Collider Component to your Player and Enemy Prefabs:
- [ ] Create a CollisionManager Script:
- [ ] **Modify the Enemy Script:**  Add a method `HandleCollisionWithPlayer()` in your `Enemy` script to handle the collision behavior.
- [ ] Attach the CollisionManager Script:
```
git fetch origin
git checkout 57-enemy-spinning
```

**Comment by MikeMMattinson** [comment]
Here are a few steps you can take to address the spinning issue:

Check Collision Handling:
Make sure that your player and enemy game objects have appropriate colliders and rigidbodies attached to them. Ensure that the collision detection settings are suitable for your game's requirements. For instance, you might want to use triggers for detection without physical interaction or handle collisions using physics.
Collision Detection Method:
If you are using collision detection methods such as OnCollisionEnter2D or OnTriggerEnter2D in your scripts, review the code inside these methods. Ensure that you handle the collision behavior correctly without causing unwanted rotations or movements.
Adjust Physics Properties:
Depending on your game's physics settings, you may need to adjust properties such as friction, mass, or constraints to prevent spinning when collisions occur.
Debugging Collision Issues:
Use Unity's debugging tools to visualize collisions and rigidbody interactions. You can enable gizmos, debug logs, or breakpoints in your scripts to understand when and why the spinning occurs.

**Comment by nickmattinson** [comment]
```
using UnityEngine;

public class EnemyController : MonoBehaviour
{
    private bool rotating = true; // Flag to control enemy rotation

    private void Update()
    {
        if (rotating)
        {
            // Rotate the enemy as needed
            // Example: transform.Rotate(Vector3.up * Time.deltaTime * rotationSpeed);
        }
    }

    private void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.CompareTag("Player"))
        {
            // If collided with the player, stop rotating
            rotating = false;
        }
    }
}

```
